# Generated by Django 3.1.4 on 2020-12-22 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=255)),
                ('image_categorie', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomcl', models.CharField(max_length=255)),
                ('prenomcl', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomf', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noming', models.CharField(max_length=255)),
                ('unite', models.CharField(choices=[('kg', 'kg'), ('L', 'L')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomst', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datev', models.DateField(auto_now_add=True)),
                ('heur', models.TimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.client')),
            ],
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_plat', models.CharField(max_length=255)),
                ('prix_plat', models.CharField(max_length=255)),
                ('datecreation', models.DateTimeField(auto_now_add=True)),
                ('imagplat', models.ImageField(blank=True, null=True, upload_to='')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.categorie')),
                ('statut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.statut')),
            ],
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitev', models.FloatField(max_length=255)),
                ('plat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.plat')),
                ('vente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.vente')),
            ],
        ),
        migrations.CreateModel(
            name='LigneIgredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtip', models.FloatField(max_length=255)),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.ingredient')),
                ('plat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.plat')),
            ],
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unite', models.CharField(max_length=255)),
                ('achat', models.FloatField(max_length=255)),
                ('vente', models.FloatField(max_length=255)),
                ('resultat', models.FloatField(max_length=255)),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datachat', models.DateTimeField(auto_now_add=True)),
                ('qtachat', models.FloatField(max_length=255)),
                ('prixachat', models.FloatField(max_length=255)),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.fournisseur')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.ingredient')),
            ],
        ),
    ]
