# Generated by Django 3.1.4 on 2020-12-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='prix_plat',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='plat',
            name='statut',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
