# Generated by Django 3.1.4 on 2020-12-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201222_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unite',
            field=models.CharField(choices=[('kg', 'kg'), ('L', 'L'), ('u', 'u')], max_length=255, null=True),
        ),
    ]
