# Generated by Django 3.1.4 on 2020-12-28 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20201228_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='achat',
            name='prixachat',
        ),
        migrations.CreateModel(
            name='LigneAchat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtachat', models.FloatField(max_length=255)),
                ('prixachat', models.FloatField(max_length=255)),
                ('achat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.ingredient')),
            ],
        ),
    ]
