# Generated by Django 3.1.4 on 2020-12-28 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20201228_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='qtachat',
        ),
    ]
