# Generated by Django 3.1.4 on 2021-01-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20201229_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='prix_plat',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
