# Generated by Django 3.1.4 on 2021-01-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_table_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='numtab',
            field=models.IntegerField(null=True),
        ),
    ]
