

from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django_filters.views import FilterView
urlpatterns = [

    path('', views.defaultlogin),
    path('index', views.index, name="index"),
    path('productcata', views.productcata, name="productcata"),
    path('productlist', views.productlist, name="productlist"),
    path('productgrid/<str:pk>/', views.productgrid, name="productgrid"),
    path('addproduct.html', views.create, name="addproduct"),
    path('updateplat/<str:pk>/', views.updateplat, name="updateplat"),
    path('detailplat/<str:pk>/', views.detailplat, name="detailplat"),
    path('deleteplat/<str:pk>/', views.deleteplat, name="deleteplat"),
    path('orders', views.orders, name="orders"),
    path('detailcommande/<str:pk>/', views.detailcommande, name="detailcommande"),
    path('tablelist', views.tablelist, name="tablelist"),
    path('basic-tables', views.basictables, name="basictables"),
    path('data-tables', views.datatables, name="datatables"),
    path('user-profile/', views.userprofile, name="userprofile"),
    path('updatuser/<str:pk>/', views.updatuser, name="updatuser"),
    path('form-layout', views.adduser, name="adduser"),
    path('default-login', views.defaultlogin, name="defaultlogin"),
    path('deleteuser/<str:pk>/', views.deleteuser, name="deleteuser"),
    path('logout/', views.LogOutUser, name="logout"),
    path('login/', views.lock, name="login"),
    path('lock-screen', views.lock, name="lock"),
    path('delete/<str:pk>/', views.Delete, name="delete"),
    path('addcat', views.AddCat, name="addcat"),
    path('updatecat/<str:pk>/', views.updatecat, name="updatecat"),
    path('addtable', views.addtable, name="addtable"),
    path('deletetable/<str:pk>/', views.deletetable, name="deletetable"),
    path('updatetable/<str:pk>/', views.updatetable, name="updatetable"),
    path('addorder', views.addorder, name="addorder"),
    path('deleteorder/<str:pk>/', views.deleteorder, name="deleteorder"),
    path('updateorder/<str:pk>/', views.updateorder, name="updateorder"),
    path('inventaire', views.inventaire, name="inventaire"),
    path('inventaire1m', views.inventaire1m, name="inventaire1m"),
    path('inventaire3m', views.inventaire3m, name="inventaire3m"),
    path('inventaire6m', views.inventaire6m, name="inventaire6m"),
    path('achat', views.achat, name="achat"),
    path('addachat', views.addachat, name="addachat"),
    path('updatachat/<str:pk>/', views.updatachat, name="updatachat"),
    path('deletachat/<str:pk>/', views.deletachat, name="deletachat"),
    path('detailachat/<str:pk>/', views.detailachat, name="detailachat"),
    path('addfournisseur', views.addfournisseur, name="addfournisseur"),
    path('fournisseur', views.fournisseur, name="fournisseur"),
    path('deletfournisseur/<str:pk>/', views.deletfournisseur, name="deletfournisseur"),
    path('updatefournisseur/<str:pk>/', views.updatefournisseur, name="updatefournisseur"),
    path('inglist', views.inglist, name="inglist"),
    path('adding', views.adding, name="adding"),
    path('updating/<str:pk>/', views.updating, name="updating"),
    path('delting/<str:pk>/', views.delting, name="delting"),
    path('menu', views.menu, name="menu"),
    path('listeplat/<str:pk>', views.listeplat, name="listeplat"),
    path('menuing/<str:pk>', views.menuing, name="menuing"),
    path('commander', views.commander, name="commander"),
    path('updatep/<str:pk>', views.updatep, name="updatep"),
    path('prevision_chart/', views.prevision_chart, name='prevision_chart'),
    path('cuisine', views.cuisine, name='cuisine'),
    path('cmdetail/<str:pk>', views.cmdetail, name='cmdetail'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
